version: '3'
services:
  sinkrait-course-api: 
    image: "sinkrait-course-api:lastest"
    build: 
      context: .
      dockerfile: ./docker/Dockerfile.prod
    container_name: "sinkrait-course-api"
    restart: always
    ports:
      - "80:8000"
    volumes:
      - ./.env:/app/.env
