version: '3'
services:
  course-api-db-test:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=course
    ports:
      - '5432:5432'
    volumes:
      - 'pgdata:/var/lib/postgresql/data/'
    # volumes: 
    #   - db:/var/lib/postgresql/data
volumes:
  pgdata: