# PROD config
FROM node:14-alpine as prod

WORKDIR /app

ADD package.json package.json

RUN npm install

ADD . .

RUN npx prisma generate

RUN npm run build
RUN npm prune --production
CMD ["node", "./dist/main.ts"]
